seed_everything: 42

# ---------------------------- TRAINER -------------------------------------------
trainer:
  default_root_dir: /eagle/MDClimSim/tungnd/india_benchmark/

  precision: bf16-mixed

  devices: 1
  num_nodes: 1
  accelerator: gpu
  strategy: ddp

  min_epochs: 1
  max_epochs: 100
  enable_progress_bar: true

  sync_batchnorm: True
  enable_checkpointing: True
  num_sanity_val_steps: 1

  # debugging
  fast_dev_run: false

  logger:
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
    init_args:
      project: 'india_benchmark'
      save_dir: ${trainer.default_root_dir}/test
      name: test

  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "step"

    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: "${trainer.default_root_dir}/test/checkpoints"
        monitor: "val/w_mse_agg" # name of the logged metric which determines when model is improving
        mode: "min"
        save_top_k: 1 # save k best models (determined by above metric)
        save_last: True # additionaly always save model from last epoch
        verbose: False
        filename: "epoch_{epoch:03d}"
        auto_insert_metric_name: False

    # - class_path: lightning.pytorch.callbacks.EarlyStopping
    #   init_args:
    #     monitor: "val/loss"
    #     mode: "min"
    #     patience: 10 # how many validation epochs of not improving until training stops
    #     min_delta: 0. # minimum change in the monitored metric needed to qualify as an improvement

    - class_path: lightning.pytorch.callbacks.RichModelSummary
      init_args:
        max_depth: -1

    - class_path: lightning.pytorch.callbacks.TQDMProgressBar

# ---------------------------- MODEL -------------------------------------------
model:
  vars_to_log: [
    TMP,
    UGRD,
    VGRD,
    PRMSL,
    HGT500,
    TMP_prl850,
    TMP_prl500,
    UGRD_prl850,
    UGRD_prl500,
    VGRD_prl850,
    VGRD_prl500,
    RH850,
    RH700,
    RH500
  ]
  lr: 2e-4
  beta_1: 0.9
  beta_2: 0.95
  weight_decay: 1e-5
  warmup_epochs: 10
  max_epochs: 100
  warmup_start_lr: 1e-8
  eta_min: 1e-8
  net:
    class_path: india_benchmark.models.neural_lam.models.hi_lam.HiLAM
    init_args:
      img_size: [256, 256]
      variables: ${data.local_variables}
      n_input_steps: 2
      graph_dir_path: /eagle/MDClimSim/tungnd/data/imdaa/hierarchical_graph
      hidden_dim: 128
      hidden_layers: 1
      processor_layers: 16

# ---------------------------- DATA -------------------------------------------
data:
  global_root_dir: /eagle/MDClimSim/tungnd/data/wb2/0.25deg_1_step_6hr_h5df_cropped_for_imdaa
  global_variables: [
    '2m_temperature',
    '10m_u_component_of_wind',
    '10m_v_component_of_wind',
    'mean_sea_level_pressure',
    'geopotential_925',
    'geopotential_850',
    'geopotential_700',
    'geopotential_600',
    'geopotential_500',
    'geopotential_250',
    'geopotential_50',
    'temperature_925',
    'temperature_850',
    'temperature_700',
    'temperature_600',
    'temperature_500',
    'temperature_250',
    'temperature_50',
    'u_component_of_wind_925',
    'u_component_of_wind_850',
    'u_component_of_wind_700',
    'u_component_of_wind_600',
    'u_component_of_wind_500',
    'u_component_of_wind_250',
    'u_component_of_wind_50',
    'v_component_of_wind_925',
    'v_component_of_wind_850',
    'v_component_of_wind_700',
    'v_component_of_wind_600',
    'v_component_of_wind_500',
    'v_component_of_wind_250',
    'v_component_of_wind_50',
    'specific_humidity_925',
    'specific_humidity_850',
    'specific_humidity_700',
    'specific_humidity_600',
    'specific_humidity_500',
    'specific_humidity_250',
    'specific_humidity_50',
  ]
  local_root_dir: /eagle/MDClimSim/tungnd/data/imdaa/imdaa_bench_h5
  local_variables: [
    TMP,
    UGRD,
    VGRD,
    PRMSL,
    HGT925,
    HGT850,
    HGT700,
    HGT600,
    HGT500,
    HGT250,
    HGT50,
    TMP_prl925,
    TMP_prl850,
    TMP_prl700,
    TMP_prl600,
    TMP_prl500,
    TMP_prl250,
    TMP_prl50,
    UGRD_prl925,
    UGRD_prl850,
    UGRD_prl700,
    UGRD_prl600,
    UGRD_prl500,
    UGRD_prl250,
    UGRD_prl50,
    VGRD_prl925,
    VGRD_prl850,
    VGRD_prl700,
    VGRD_prl600,
    VGRD_prl500,
    VGRD_prl250,
    VGRD_prl50,
    RH925,
    RH850,
    RH700,
    RH600,
    RH500,
    RH250,
    RH50
  ]
  train_year_start: 2000
  train_year_end: 2017
  val_year_start: 2018
  val_year_end: 2018
  test_year_start: 2019
  test_year_end: 2019
  padding_factor: 0.0
  ignore_last_local_files: 0
  lead_time: 6
  data_freq: 6
  n_input_steps: 1
  n_output_steps: 1
  n_test_outoput_steps: 12
  batch_size: 2
  num_workers: 4
  pin_memory: False